[package]
name = "task-manager-cli-rust"
version = "0.1.0"
authors = ["Renan Pinheiro <renanpinheirodesouza3@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "task-manager-cli-rust"
path = "src/main.rs"
